### ISSUE TITLE
Breakage: Tweakers.net

### ISSUE THREAD

**Issue by crisp-tweakers** [BPower0036/AdBlockFilters#18] opened 2021-05-13 08:46 UTC
- [X] This is a **Dutch** website, so no general websites with Dutch subdomains (e.g. nl.y8.com) / 
      Het is een **Nederlandse** website, dus geen websites met Nederlandse subdomeinen (bijv. nl.y8.com)
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue / Geen **duplicaten**!!
    - Your issue may already be reported. / Uw probleem kan al gemeld zijn.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
    - [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie
    - [X] disabling the EasyDutch list
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
    - Privacy staff should be reported at uBlock Origin or EasyPrivacy / Privacy dingen moet u melden aan uBlock of EasyPrivacy
    - No annoyances 

Urls and problems:
- https://tweakers.net/nieuws/181610/apple-ontslaat-pas-aangeworven-manager-na-protest-personeel.html (no comments visible)

![image](https://user-images.githubusercontent.com/32640525/118101688-26313900-b3d8-11eb-90f5-fa675f1126ce.png)

- https://tweakers.net/smartphones/vergelijken/ (no listing visible)

![image](https://user-images.githubusercontent.com/32640525/118101619-16b1f000-b3d8-11eb-8287-55b5f8e8ed21.png)

Versions:
- Browser/version: Firefox 88.0.1
- uBlock Origin version: 1.35.2

It seems the (new) rules added yesterday are responsible for this, hiding more than they should.

See also the bugreports on our site:
- https://gathering.tweakers.net/forum/list_messages/2071116
- https://gathering.tweakers.net/forum/list_messages/2071078

**Comment by Vistaus** [comment] 2021-05-13 09:53
I can confirm this issue. Please fix it so that we can browse Tweakers again and view comments again.

**Comment by nicolaasjan** [comment] 2021-05-13 11:00
Just came here to report this breakage, but I see it's already reported, haha.
Disabled EasyDutch for now.

**Comment by Mace404** [comment] 2021-05-13 11:19
This is the rule breaking the content list:
`tweakers.net##[id="layout"] > [id="contentArea"] > [class="wrap"] > [id^="tab"] > [class] > [id] > [id]:has(img[src^="https://tweakers.net/i/"])`

**Comment by EchoDev** [comment] 2021-05-13 11:24
These (EasylistDutch) rules are breaking the site

```
tweakers.net##[id="layout"] > [id="contentArea"] > [class="wrap"] > [id]:has(img[src^="https://tweakers.net/i/"]):not([id^="tab"]):not([id="content"]):not([id^="forum"])
tweakers.net##[id="layout"] > [id="contentArea"] > [class="wrap"] > [id^="tab"] > [class] > [class]:has(img[src^="https://tweakers.net/i/"]):not([class^="product"])
tweakers.net##[id="layout"] > [id="contentArea"] > [class="wrap"] > [id^="tab"] > [class] > [id] > [id]:has(img[src^="https://tweakers.net/i/"])
tweakers.net##[id="top"] > [id="entity"] > div > [id]:has(img[src^="https://tweakers.net/i/"])
```

Replace `tweakers.net##` with `tweakers.net#@#` to override the rules and temporarily fix these issues

**Comment by nicolaasjan** [comment] 2021-05-13 13:27
> Replace `tweakers.net##` with `tweakers.net#@#` to override the rules and temporarily fix these issues

Thanks!
That works for now.

Will you mention it here when it's fixed in the list?

**Comment by Shinevision** [comment] 2021-05-13 14:51
I can confirm that allowing these rules fixes it:

`@@||tweakers.net/i/*/1280x400/filters:max_bytes(102400):strip_icc()/i/*.jpeg?f=thumblarge`

and

`tweakers.net#@#[id="layout"] > [id="contentArea"] > [class="wrap"] > [id]:has(img[src^="https://tweakers.net/i/"]):not([id^="tab"]):not([id="content"]):not([id^="forum"])`

**Comment by rjgotten** [comment] 2021-05-13 21:33
FYI:
Neither EchoDev nor Shinevision's suggestion works ATM for me.
Reactions/comments on Tweakers.net remain broken.

**Comment by BPower0036** [comment] 2021-05-14 06:46
@rjgotten @Vistaus @EchoDev @nicolaasjan @Shinevision @Mace404 I'm sorry for the inconvenience. I tried to block the coolblue ad *with* the word 'advertentie'. But some how it causes more breakage then is solves things. 
So if you have a better idea to block this, please let me know.

**Comment by BPower0036** [comment] 2021-05-14 06:58
It seems that tweakers is constantly changing their website, because I can't find this kind of ads anymore.
![image](https://user-images.githubusercontent.com/80090789/118233672-82589380-b492-11eb-8520-6b7381b1bb7c.png)

**Comment by BPower0036** [comment] 2021-05-14 07:05
Because uBlock Origin also solves tweakers.net issues, (They recently added this rule: https://github.com/uBlockOrigin/uAssets/commit/96a413e44e26eaaa7a7cd69348ab9ae79f74511f#diff-03b955eebef8886aa0f1ef70b305e9b7996de9a9e0adc9fe002db5a21d301c9fR142)
I'm going to try to solve any issues on tweakers.net If you have a issue please report it to uBlock Origin

**Closed by BPower0036** 2021-05-14 07:05 UTC

**Comment by nicolaasjan** [comment] 2021-05-14 08:21
>  I'm going to try to solve any issues on tweakers.net If you have a issue please report it to uBlock Origin

I think you meant:
I'm **not** going to try to solve any issues on tweakers.net ;)

**Comment by BPower0036** [comment] 2021-05-14 08:46
@nicolaasjan Yes, that is what I mean
